mod day01;
mod day02;
mod day03;
mod day03_alt;
mod day04;
mod day05;
mod day06;
mod day07;
mod day08;
mod day09;
mod day10;
mod day11;
mod day12;
mod day13;
mod day14;
mod day15;
mod day16;
mod day17;
mod day18;
mod day19;
mod day20;
mod day21;
mod day22;
mod utils;

fn main() {
    println!("Advent of Code 2024 Rust \n");
    //println!("Day 1:");
    //day01::solve();
    //println!("Day 2:");
    //day02::solve();
    //println!("Day 3:");
    //day03::solve();
    //println!("Day 3 Parser Solution:");
    //day03_alt::solve();
    //println!("Day 4:");
    //day04::solve();
    //println!("Day 5:");
    //day05::solve();
    //println!("Day 6:");
    //day06::solve();
    //println!("Day 7:");
    //day07::solve();
    //println!("Day 8:");
    //day08::solve();
    //println!("Day 9:");
    //day09::solve();
    //println!("Day 10:");
    //day10::solve();
    //println!("Day 11:");
    //day11::solve();
    //println!("Day 12:");
    //day12::solve();
    //println!("Day 13:");
    //day13::solve();
    //println!("Day 14:");
    //day14::solve();
    //println!("Day 15:");
    //day15::solve();
    //println!("Day 16:");
    //day16::solve();
    //println!("Day 17:");
    //day17::solve();
    //println!("Day 18:");
    //day18::solve();
    //println!("Day 19:");
    //day19::solve();
    //println!("Day 21:");
    //day21::solve();
    println!("Day 22:");
    day22::solve();
}
